include_configs:
  - ../../train/diffusion/diffusion_16x16x16_dense.yaml
  - plane.yaml

name: 'shapenet/plane_diffusion_dense'

vae_config: "/home/ncaytuir/data-local/XCube_necs/configs/shapenet/plane/train_vae_16x16x16_dense.yaml"
vae_checkpoint: "/home/ncaytuir/data-local/wandb/xcube-shapenet/y98joza4/checkpoints/last.ckpt"